config:
  send_anonymous_usage_stats: False

default:
  target: dev

  outputs:
    dev:
      type: postgres
      host: localhost
      user: ''
      pass: ''
      port: 5432
      dbname: analytics
      schema: core
      threads: 8
